/** Declaration file generated by dts-gen */

export = Blowfish;

declare class Blowfish {
    constructor(r: any, n: any, a: any);
    decode(r: any, i: any): any;
    encode(r: any): any;
    setIv(r: any): void;
    static MODE: {
        CBC: number;
        ECB: number;
    }
    static PADDING: {
        LAST_BYTE: number;
        NULL: number;
        ONE_AND_ZEROS: number;
        PKCS5: number;
        SPACES: number;
    }
    static TYPE: {
        STRING: number;
        UINT8_ARRAY: number;
    }
}
declare namespace Blowfish {
    function decode(r: any, i: any): any;
    function encode(r: any): any;
    function setIv(r: any): void;
}
